I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 245, in script
    current_character "Ура! Кастрюльки для бабушки, первый подарок найден!"
Exception: Sayer 'current_character' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 245, in script
    current_character "Ура! Кастрюльки для бабушки, первый подарок найден!"
  File "C:\Users\Анастасия\Desktop\other\python\renpy-8.3.3-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\Анастасия\Desktop\other\python\renpy-8.3.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Анастасия\Desktop\other\python\renpy-8.3.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'current_character' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24111502
christmas cat 1.0
Mon Dec 16 01:20:38 2024
